### PR TITLE
Fix various spelling errors

### PR DESCRIPTION
**Pull request by ottok**
e.g.
- succesfully -> successfully
- preceeding -> preceding

### CODE REVIEW

**Comment by ottok** [comment]
Ping @janlindstrom or @temeo ?

**Comment by ottok** [comment]
I have now rebased this on laters master. Merging this spelling error fix should be trivial. Please @ayurchen or @mkaruza?

**Comment by ottok** [comment]
Please merge @temeo

**Comment by ottok** [comment]
Please merge @temeo

**Comment by ottok** [comment]
@temeo Rebased on latest master again. Could you please merge this now?

**Comment by temeo** [comment]
@ottok Please rebase and add yourself in CONTRIBUTORS.txt

**Comment by ottok** [comment]
PR updated with CONTRIBUTORS.txt amended.

**Review by temeo — APPROVED** [review]

**Pull request merged**
